name: spoonacular
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

isar_version: &isar_version 3.1.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  provider: ^6.1.2
  flutter_widget_from_html: ^0.15.0
  dio: ^5.4.3+1
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  mobx_codegen: ^2.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  json_serializable: ^6.1.7
  isar: *isar_version
  isar_flutter_libs: *isar_version
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  freezed: ^2.5.2
  build_runner: ^2.4.10
  isar_generator: *isar_version

flutter:
  uses-material-design: true
