// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbaLah6B9Fs5FMJO1FzhaBbVFK4q5jWOc',
    appId: '1:542140510710:web:38552771fa399546a297d7',
    messagingSenderId: '542140510710',
    projectId: 'spoonacular-food',
    authDomain: 'spoonacular-food.firebaseapp.com',
    storageBucket: 'spoonacular-food.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpBzJSVIOFG0K4ygS_WxTxybJ42BEWzjM',
    appId: '1:542140510710:android:c943fc13244f3342a297d7',
    messagingSenderId: '542140510710',
    projectId: 'spoonacular-food',
    storageBucket: 'spoonacular-food.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWr9NMnXHQuoyIn_ScWiNb6d53jectmRY',
    appId: '1:542140510710:ios:c7a3d434359cef28a297d7',
    messagingSenderId: '542140510710',
    projectId: 'spoonacular-food',
    storageBucket: 'spoonacular-food.appspot.com',
    iosBundleId: 'com.example.spoonacular',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWr9NMnXHQuoyIn_ScWiNb6d53jectmRY',
    appId: '1:542140510710:ios:c7a3d434359cef28a297d7',
    messagingSenderId: '542140510710',
    projectId: 'spoonacular-food',
    storageBucket: 'spoonacular-food.appspot.com',
    iosBundleId: 'com.example.spoonacular',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbaLah6B9Fs5FMJO1FzhaBbVFK4q5jWOc',
    appId: '1:542140510710:web:fab5401fc36cd4d3a297d7',
    messagingSenderId: '542140510710',
    projectId: 'spoonacular-food',
    authDomain: 'spoonacular-food.firebaseapp.com',
    storageBucket: 'spoonacular-food.appspot.com',
  );
}
